SELECT CITY, LENGTH(CITY) FROM (SELECT CITY, LENGTH(CITY) AS L FROM STATION
ORDER BY L,CITY)
WHERE ROWNUM <= 1;
SELECT CITY, LENGTH(CITY) FROM (SELECT CITY, LENGTH(CITY) AS L FROM STATION
ORDER BY L DESC)
WHERE ROWNUM <= 1;
